name: Lighthouse

on:
  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Lighthouse Audit
      uses: browniebroke/lighthouse-action@netlify-deploy-integration
      with:
        url: 'https://browniebroke.com/'
        netlify_site: 'browniebroke.netlify.com'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
