name: Lighthouse

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Debug env
      run: env
    - name: Expose event data
      run: cat ${GITHUB_EVENT_PATH}
    - name: Get PR ID
      run: export GH_PULL_REQUEST_NUMBER=$(jq .number ${GITHUB_EVENT_PATH})
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@v0.1.0
      with:
        url: "https://deploy-preview-${GH_PULL_REQUEST_NUMBER}--browniebroke.netlify.com/"
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'

