name: Lighthouse

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@v0.1.0
      with:
        url: 'https://browniebroke.com'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'

